[azure]
disabled = false

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true

[git_status]
conflicted = ""
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
