# Action to get the latest release information for a given environment configuration.

name: get-latest-release-information
description: Get the latest release information for this environment config.

inputs:
  release-prefix:
    description: The prefix of the environment configuration.
    required: true
  github-releases-url:
    description: The GitHub releases URL.
    required: true
outputs:
  release-name:
    description: The name of the latest release.
    value: ${{ steps.latest-release.outputs.release-name }}
  release-tag:
    description: The Git tag of the latest release.
    value: ${{ steps.latest-release.outputs.release-tag }}
  version-number:
    description: The version of the latest release.
    value: ${{ steps.latest-release.outputs.version-number }}
  major-version-number:
    description: The major version number of the latest release.
    value: ${{ steps.latest-release.outputs.major-version-number }}
  minor-version-number:
    description: The minor version number of the latest release.
    value: ${{ steps.latest-release.outputs.minor-version-number }}
  build-version-number:
    description: The build version number of the latest release.
    value: ${{ steps.latest-release.outputs.build-version-number }}
  download-url:
    description: The download URL of the latest release.
    value: ${{ steps.latest-release.outputs.download-url }}
  file-hash:
    description: The SHA 512 hash of the latest release version.
    value: ${{ steps.latest-release.outputs.file-hash }}
  folder-hash:
    description: The SHA 512 hash of all files of the latest release version.
    value: ${{ steps.latest-release.outputs.folder-hash }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
runs:
  using: composite
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    - name: Get Latest Tag
      id: get-latest-tag
      uses: oprypin/find-latest-tag@v1.1.1
      with:
        repository: jasonmcboyd/Environment
        releases-only: true
        prefix: "${{ inputs.release-prefix }}-v"

    # I have to jump through a lot of hoops here to verify the hash. For some reason the hash changes after a zip has been
    # uploaded to GitHub. I think during the upload they decompress and then recompress with their algorithm of choice which
    # is different from Compress-Archive. The different algorithm results in a different zip file with a different file hash.
    - name: Get Latest Release Information
      id: latest-release
      shell: powershell
      run: |
        $latestReleaseTag = '${{ steps.get-latest-tag.outputs.tag }}'
        $releaseInfo =
          ./Publish/PowerShellScripts/GetGitHubReleaseInfo.ps1 `
            -ReleaseTag $latestReleaseTag `
            -GitHubReleasesUrl ${{ inputs.github-releases-url }}

        ./Publish/PowerShellScripts/WriteGitHubOutputs.ps1 -HashTable $releaseInfo
