# This is a basic workflow to help you get started with Actions

name: get-latest-release-information

inputs:
  release-prefix:
    required: true
    type: string
outputs:
  latest-release:
    value: ${{ steps.latest-release.outputs.latest-release }}
  latest-release-major-version-number:
    value: ${{ steps.latest-release.outputs.latest-release-major-version-number }}
  latest-release-version-number:
    value: ${{ steps.latest-release.outputs.latest-release-version-number }}
  latest-release-url:
    value: ${{ steps.latest-release.outputs.latest-release-url }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get Latest Tag
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1.1.1
        with:
          repository: jasonmcboyd/Environment
          releases-only: true
          prefix: "${{ inputs.release-prefix }}-v"

      - name: Get Latest Release Information
        id: latest-release
        run: |
          $latestRelease = '${{ steps.get-latest-tag.outputs.tag }}'
          $latestRelease -match '${{ inputs.release-prefix }}-v(?<major>\d+)\.' | Out-Null
          $majorVersionNumber = $Matches.major
          $versionNumber = "$majorVersionNumber.0.0"
          $latestReleaseUrl = "https://github.com/jasonmcboyd/Environment/releases/download/$latestRelease/${{ inputs.release-prefix }}.zip"
          echo "latest-release=$latestRelease" >> $env:GITHUB_OUTPUT
          echo "latest-release-major-version-number=$majorVersionNumber" >> $env:GITHUB_OUTPUT
          echo "latest-release-version-number=$versionNumber" >> $env:GITHUB_OUTPUT
          echo "latest-release-url=$latestReleaseUrl" >> $env:GITHUB_OUTPUT
          echo "Latest Release: $latestRelease"
          echo "Latest Release Major Version Number: $majorVersionNumber"
          echo "Latest Release Version Number: $versionNumber"
          echo "Latest Release URL: $latestReleaseUrl"
