# This is a basic workflow to help you get started with Actions

name: get-changed-files-count

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    env:
      SUBDIRECTORY: ''
      RELEASE_PREFIX: ''

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get Files Changed Count
        id: files-changed-count
        run: echo "::set-output name=COUNT::$((git diff HEAD~ --name-only -- ./${{ env.SUBDIRECTORY}} ./.github/workflows/${{ env.RELEASE_PREFIX }}.yml ./Nuspec/environment-${{ env.RELEASE_PREFIX }} | Measure-Object).Count)"

      - name: Write Files Changed Count
        run: echo "${{ steps.files-changed-count.outputs.COUNT }}"
