# This is a basic workflow to help you get started with Actions

name: PowerShell Core Profile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-release:
    uses: jasonmcboyd/Environment/.github/workflows/publish-release.yml@master
    with:
      subdirectory: PowerShellProfile
      release-prefix: powershell-core-profile
      files-to-archive: ./PowerShellProfiles/CurrentUserAllHosts/*
    secrets:
      AZURE_DEVOPS_NUGET_FEED: ${{ secrets.AZURE_DEVOPS_NUGET_FEED }}
      AZURE_DEVOPS_USERNAME: ${{ secrets.AZURE_DEVOPS_USERNAME }}
      AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
  publish-chocolatey-package:
    needs: publish-release
    uses: jasonmcboyd/Environment/.github/workflows/publish-chocolatey-package.yml@master
    with:
      release-prefix: vim-config
    secrets:
      AZURE_DEVOPS_NUGET_FEED: ${{ secrets.AZURE_DEVOPS_NUGET_FEED }}
      AZURE_DEVOPS_USERNAME: ${{ secrets.AZURE_DEVOPS_USERNAME }}
      AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
