# This is a basic workflow to help you get started with Actions

name: Publish Release And Chocolatey Package

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      subdirectory:
        required: true
        type: string
      release-prefix:
        required: true
        type: string
      files-to-archive:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-release:
    uses: jasonmcboyd/Environment/.github/workflows/publish-release.yml@master
    with:
      subdirectory: ${{ inputs.subdirectory }}
      release-prefix: ${{ inputs.release-prefix }}
      files-to-archive: ${{ inputs.files-to-archive }}
    secrets: inherit
  publish-chocolatey-package:
    needs: publish-release
    uses: jasonmcboyd/Environment/.github/workflows/publish-chocolatey-package.yml@master
    with:
      release-prefix: ${{ inputs.release-prefix }}
    secrets: inherit
