# This is a basic workflow to help you get started with Actions

name: Publish All Environment Settings And Configurations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  powershell-core-profile:
    uses: jasonmcboyd/Environment/.github/workflows/Core/publish-release-and-chocolatey-package.yml@master
    with:
      subdirectory: PowerShellProfile
      release-prefix: powershell-core-profile
      files-to-archive: ./PowerShellProfile/CurrentUserAllHosts/*
    secrets: inherit
  starship-config:
    uses: jasonmcboyd/Environment/.github/workflows/Core/publish-release-and-chocolatey-package.yml@master
    with:
      subdirectory: Starship
      release-prefix: starship-config
      files-to-archive: ./Starship/*
    secrets: inherit
  vim-config:
    uses: jasonmcboyd/Environment/.github/workflows/Core/publish-release-and-chocolatey-package.yml@master
    with:
      subdirectory: Vim
      release-prefix: vim-config
      files-to-archive: ./Vim/*
    secrets: inherit
  windows-terminal-settings:
    uses: jasonmcboyd/Environment/.github/workflows/Core/publish-release-and-chocolatey-package.yml@master
    with:
      subdirectory: WindowsTerminal
      release-prefix: windows-terminal-settings
      files-to-archive: ./WindowsTerminal/*
    secrets: inherit
