# This is a basic workflow to help you get started with Actions

name: Publish All Environment Settings And Configurations

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  powershell-core-profile:
    uses: jasonmcboyd/Environment/.github/workflows/publish-release-and-chocolatey-package.yml@master
    with:
      github-releases-url: ${{ vars.RELEASES_URL }}
      release-prefix: powershell-core-profile
      subdirectory: PowerShellProfiles/CurrentUserAllHosts
    secrets: inherit
  starship-config:
    uses: jasonmcboyd/Environment/.github/workflows/publish-release-and-chocolatey-package.yml@master
    with:
      github-releases-url: ${{ vars.RELEASES_URL }}
      release-prefix: starship-config
      subdirectory: Starship
    secrets: inherit
  vim-config:
    uses: jasonmcboyd/Environment/.github/workflows/publish-release-and-chocolatey-package.yml@master
    with:
      github-releases-url: ${{ vars.RELEASES_URL }}
      release-prefix: vim-config
      subdirectory: Vim
    secrets: inherit
  windows-terminal-settings:
    uses: jasonmcboyd/Environment/.github/workflows/publish-release-and-chocolatey-package.yml@master
    with:
      github-releases-url: ${{ vars.RELEASES_URL }}
      release-prefix: windows-terminal-settings
      subdirectory: WindowsTerminal
    secrets: inherit
