# This is a basic workflow to help you get started with Actions

name: Publish Release And Chocolatey Package

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      azure-devops-nuget-url-v3:
        required: true
        type: string
      azure-devops-username:
        required: true
        type: string
      github-releases-url:
        required: true
        type: string
      release-prefix:
        required: true
        type: string
      subdirectory:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish-release:
    uses: jasonmcboyd/Environment/.github/workflows/publish-release.yml@master
    with:
      github-releases-url: ${{ inputs.github-releases-url }}
      release-prefix: ${{ inputs.release-prefix }}
      subdirectory: ${{ inputs.subdirectory }}
    secrets: inherit
  publish-chocolatey-package:
    needs: publish-release
    uses: jasonmcboyd/Environment/.github/workflows/publish-chocolatey-package.yml@master
    with:
      azure-devops-nuget-url-v3: ${{ inputs.azure-devops-nuget-url-v3 }}
      azure-devops-username: ${{ inputs.azure-devops-username }}
      github-releases-url: ${{ inputs.github-releases-url }}
      release-prefix: ${{ inputs.release-prefix }}
    secrets: inherit
