# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: jasonmcboyd/Environment/.github/workflows/get-changed-files-count.yml@bdc376a312d3b9912550d83a7acc44c72f6e5f55
