# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Hash the Vim folder
      - name: Folder Hash
        id: folder-hash
        uses: theowenyoung/folder-hash@dbee806babae73233242b3b50270e96ad1b46fd7
        with:
          path: ./Vim

      # Test hash output
      - name: Write Hash
        run: echo "${{ steps.folder-hash.outputs.hash }}"

      # Test diff count
      - name: File Diff Count
        id: file-diff-count
        run: echo "::set-output name=FILE_DIFF_COUNT::$(git diff HEAD~ --name-only -- ./Vim | wc -l)"

      - name: Write File Diff Count
        run: echo "${{ steps.file-diff-count.outputs.FILE_DIFF_COUNT }}"

      - name: Zip Files
        # if: ${{ steps.file-diff-count.outputs.FILE_DIFF_COUNT != 0 }}
        run: zip ./Vim/* ./vim.zip

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
