# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Test diff count
      - name: File Diff Count
        id: file-diff-count
        run: echo "::set-output name=FILE_DIFF_COUNT::$(git diff HEAD~ --name-only -- ./Vim | wc -l)"

      - name: Write File Diff Count
        run: echo "${{ steps.file-diff-count.outputs.FILE_DIFF_COUNT }}"

      - name: Zip Files
        if: ${{ steps.file-diff-count.outputs.FILE_DIFF_COUNT != 0 }}
        run: zip -r -j vim.zip ./Vim

      - name: Get Previous Release
        id: get-previous-release
        # if: ${{ steps.file-diff-count.outputs.FILE_DIFF_COUNT != 0 }}
        uses: oprypin/find-latest-tag@e6d7a96b985a7dda6080e43e12771ad3a90fd389
        with:
          repository: jasonmcboyd/Environment
          releases-only: true
          prefix: "vim-"

      - name: Write Previous Release
        # if: ${{ steps.file-diff-count.outputs.FILE_DIFF_COUNT != 0 }}
        run: echo "${{ steps.get-previous-release.outputs.tag }}"

      - name: Get Version Number
        id: get-version-number
        run: echo "::set-output name=VERSION_NUMBER::$(echo {{ steps.get-previous-release.outputs.tag }} | cut -d - -f 2)"

      - name: Get Next Release Tag
        uses: christian-draeger/increment-semantic-version@1.0.2
        id: get-next-release-tag
        with:
          current-version: ${{ steps.get-version-number.outputs.VERSION_NUMBER }}
          version-fragment: 'major'

      - name: Write Next Release Tag
        run: echo "${{ steps.get-next-release-tag.outputs.next-version }}"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls
